### ISSUE TITLE
WorldEditCUI for 1.9

### ISSUE THREAD

**Issue by FrozenBeard** [Mumfrey/WorldEditCUI#10]
Any plans to get this made? I absolutely LOVE this mod; I couldn't  imagine running a server without it.

**Comment by Mumfrey** [comment]
Of course, but I only finished updating liteloader 1 day ago so give me half a chance.

**Comment by FrozenBeard** [comment]
Fantastic! Sorry, this isn't a rush post, it was just a legitimate curiosity since 1.8 dev was never officially published as a finished project, will there be a new lease of life with a fully supported 1.9 liteloader mod?

**Comment by Mumfrey** [comment]
I'm not sure where you got the impression that WECUI for 1.8 wasn't released, if you visit the forum thread [here](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292886-worldeditcui) you'll see it's listed as the main download.

**Comment by FrozenBeard** [comment]
Liteloader, I was talking about, in reply to your comment about liteloader. The website listed it as a dev only build in a small footnote of text.

**Comment by Mumfrey** [comment]
It's a long and not very interesting story, the short version is that normal fully-promoted releases are coming soon.

**Comment by Mumfrey** [comment]
In the meantime, WECUI for 1.9 is now available.

**Comment by FrozenBeard** [comment]
You got WECUI for 1.9 done in the time I created this ticket? that was 10 hours ago... you're a mad man! 
Such a boss Mumfrey, thanks a million, Ill head over and get my DL on :+1:

**Comment by Brottweiler** [comment]
@FrozenBeard well, he probably didn't start updating it from and because your ticket. He was probably already working on it, unless it took super fast. 😛

**Comment by FrozenBeard** [comment]
@Brottweiler Don't shatter my dreams, I believe Mumfrey is a coding machine.

**Comment by Mumfrey** [comment]
I did the update in my lunch break today :)
