### ISSUE TITLE
Minecraft crash 

### ISSUE THREAD

**Issue by iLefty** [Mumfrey/WorldEditCUI#13]
If I join on my server, through minecraft client are momentary crash.
Crash-report report:
https://cdn.discordapp.com/attachments/264826625705771009/267738336377044992/crash-2017-01-08_23.07.59-client.txt

**Comment by Mumfrey** [comment]
1.7.10 is no longer supported.

**Comment by iLefty** [comment]
You answered 7 months ago...

**Comment by Mumfrey** [comment]
I didn't see the notification at the time. Also this crash is not related to WECUI, it's another mod which is causing the onInitCompleted event to fire so I can't fix it here anyway.
