### ISSUE TITLE
Request: Add a chunk border viewer option

### ISSUE THREAD

**Issue by Nuinethir** [Mumfrey/WorldEditCUI#15]
This is an odd feature request, but here goes...

I run FTB modpacks with shaders. The shaders prevent the default vanilla chunk border viewer from working (F3+G), as well as the Chunk Edge Indicator mod (F9). They both seem to use the same drawing methods.

However, the WorldEditCUI is much more visible and doesn't obstruct or disappear at all. It is clear that the drawing method is superior since it bypasses the shaders. I can use WorldEdit commands **//chunk** to select the chunk and **//desel** to unselect it (which would be a good workaround), but in a survival, no-cheat world, I cannot use these commands (no permissions without editing WE's config or the save itself to enable cheats, which I would rather not do, it's a slippery slope).

Therefore, I would like to request that a chunk border viewer feature be added, that can be enabled/disabled either by hotkey or command.

Thanks for your time. :)

**Comment by Mumfrey** [comment]
Hi there, sorry I missed this issue, it was posted at a time when I was very busy IRL and I missed the notification. I will look into this for you.
