### ISSUE TITLE
WorldEditCUI doesn't display when using Optifine C8 & shaders enabled

### ISSUE THREAD

**Issue by Dockter** [Mumfrey/WorldEditCUI#18]
Doing some internal testing and found that when using WorldEditCUI + Optifine C8 and using a SUES Shader 1.0.0, that the graphical area visualization doesn't appear.  Disable the shader and it works fine.

Not sure why, would be willing to debug if you can point me in the appropriate direction.

Thanks,

**Comment by Mumfrey** [comment]
Shaders have always made the grid either almost or completely disappear, enabling "always on top" may improve things but essentially the shaders override the appearance of the rendered lines so there physically isn't much you can do about it other than disable shaders when you want to use wecui. You could try disabling different features of the shader until you find out which one nukes the lines.
