### ISSUE TITLE
Feature Request: Delete selections client sided 

### ISSUE THREAD

**Issue by Ecconia** [Mumfrey/WorldEditCUI#21]
Requst:
A client side easy-to-use reset for all selections.

Reason:
Due to developing plugins on that server which use selections. I keep using /Reload which doesn't unload the selections from the client. To remove these (now permanent) selections I have to rejoin.

Suggestion:
- A keyboard shortcut to delete all current selections, or reset them. (That would probably be the quickest way). 
- Also possible would be an entry in the liteloader-menu. At least it prevents me from leaving the server and wiping the chat history, etc.

Thanks.

**Comment by Mumfrey** [comment]
I will add an option for the "clear worldedit selection" keybind to clear server-defined selections which should allow this. For reference you would have previously been able to do this using the [Macro/Keybind Mod](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1275039-macro-keybind-mod) using the following script:

```c
SELECTCHANNEL("wecui:wecui");
SENDMESSAGE("+s|clear");
```

This would send the "clear regions" command to WECUI using the liteloader message bus.

**Comment by Mumfrey** [comment]
A new option is now available in the settings (below the colour selectors) to enable this behaviour. You can [download version 1.12.1_01 from here](http://eq2.co.uk/minecraft/mods/thirdparty/mod_worldeditcui_1.12.1_01_lite_mc1.12.1.litemod) which includes this change:

![](http://eq2.co.uk/pr/clear_on_clear.png)

**Comment by Ecconia** [comment]
Thank you very much, it works.
