### ISSUE TITLE
//sel convex unsupported

### ISSUE THREAD

**Issue by kenzierocks** [Mumfrey/WorldEditCUI#6]
I'm not sure if this is something for WE as well as WECUI, but `//sel convex` is partially unsupported. The view given by CUI looks like a regular cuboid selection.

**Comment by kenzierocks** [comment]
And this is on WorldEdit for Forge, MC 1.8, with WECUI,

**Comment by Mumfrey** [comment]
Since this [works fine on Spigot as I already mentioned](https://github.com/Mumfrey/WorldEditCUI/pull/1#issuecomment-71381437) I'm going to assume this is an issue with the forge implementation and isn't a WECUI problem.

**Comment by kenzierocks** [comment]
I'm attempting to work out the Forge problem, and I can confirm it's on the Forge side. However, I can't get the custom S3F packet to pass data from Forge to LiteLoader, do you know if there's a specific way I need to send it?

**Comment by Mumfrey** [comment]
I have no idea how plugin channel messages are handled in Forge to be honest. The protocol is quite straightforward, you simply advertise that you want to send messages on a particular channel which will cause the platform to send a REGISTER packet to the client. Then you are free to send messages on that channel.

**Comment by kenzierocks** [comment]
Huh, I think it should be working but something isn't getting through. Is there an easy way to dump the incoming packets on LiteLoader?

**Comment by Mumfrey** [comment]
Just subscribe to the channel, any mod can subscribe to any channel (except for REGISTER, which is reserved) so writing a mod to dump the incoming packets is trivial.

**Comment by kenzierocks** [comment]
I'm able to use Forge to see the packets, but LiteLoader just doesn't even call the onCustomPacket.
